// Regenerates src/data/dex.js from Showdown's public data files.
// Run with: node tools/build-dex.js
const fs = require("fs");
const path = require("path");

async function fetchJSON(url) {
  const res = await fetch(url);
  if (!res.ok) throw new Error(url + " -> HTTP " + res.status);
  return res.json();
}

async function main() {
  const pokedex = await fetchJSON("https://play.pokemonshowdown.com/data/pokedex.json");
  const movedex = await fetchJSON("https://play.pokemonshowdown.com/data/moves.json");

  const dex = {};
  for (const [id, p] of Object.entries(pokedex)) {
    if (!p.types || !p.baseStats) continue;
    // atk/spa let status severity consider the victim
    dex[id] = { t: p.types, s: p.baseStats.spe, at: p.baseStats.atk, sa: p.baseStats.spa };
  }
  const moves = {};
  for (const [id, m] of Object.entries(movedex)) {
    if (!m.type) continue;
    moves[id] = { t: m.type, c: m.category === "Status" ? 0 : 1 };
    if (m.priority) moves[id].p = m.priority;
    // accuracy only when the move can naturally miss
    if (typeof m.accuracy === "number" && m.accuracy < 100) moves[id].a = m.accuracy;
    // secondary chance, for weighting procs (100% = not luck)
    const secondaries = m.secondaries || (m.secondary ? [m.secondary] : []);
    const chances = secondaries.map((s) => s.chance).filter((c) => typeof c === "number");
    if (chances.length) moves[id].sc = Math.max(...chances);
  }

  const out =
    "// Generated by tools/build-dex.js - do not edit by hand.\n" +
    "// Species: { t: types, s: base Speed }.\n" +
    "// Moves: { t: type, c: 1 if damaging, p: priority if nonzero }.\n" +
    "window.PSMomentum = window.PSMomentum || {};\n" +
    "PSMomentum.DEX = " + JSON.stringify(dex) + ";\n" +
    "PSMomentum.MOVES = " + JSON.stringify(moves) + ";\n";

  const dest = path.join(__dirname, "..", "src", "data", "dex.js");
  fs.mkdirSync(path.dirname(dest), { recursive: true });
  fs.writeFileSync(dest, out);
  console.log(
    "wrote " + dest + ": " + Object.keys(dex).length + " species, " +
      Object.keys(moves).length + " moves, " +
      Math.round(out.length / 1024) + " KB"
  );
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
